loki:
  enabled: true
  auth_enabled: false

  server:
    http_listen_port: 3100

  storage:
    type: boltdb-shipper
    filesystem:
      directory: /data/loki
    bucketNames:
      chunks: "chunks"
      index: "index"

  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      cache_location: /data/loki/cache
      shared_store: filesystem

  commonConfig: {}

  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

  chunk_store_config:
    max_look_back_period: 0s

  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h

  compactor:
    working_directory: /data/loki/compactor
    shared_store: filesystem

  ruler:
    storage:
      type: local
    rule_path: /data/loki/rules
    alertmanager_url: http://alertmanager.monitoring.svc:9093
    ring:
      kvstore:
        store: inmemory
