name: Build and Push Docker Image

on:
  push:
    branches:
      - master   # Runs the workflow when code is pushed to master
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx (for better build performance)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .                      # root directory
          file: ./Dockerfile              # Dockerfile path
          push: true                      # Push to Docker Hub
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python-quote-logger:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/python-quote-logger:${{ github.sha }}

      # Step 5: Verify pushed image (optional)
      - name: Verify image pushed
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python-quote-logger:latest
