{{- if .Values.alloy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {{ .Release.Namespace }}
data:
  alloy.yaml: |
{{ .Values.alloy.alloy.configMap.content | indent 4 }}
{{- end }}
