{{- if .Values.alloy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
      - name: alloy
        image: grafana/alloy:latest
        args:
          - "-config.file=/etc/alloy/config/alloy.yaml"
        volumeMounts:
        - name: alloy-config
          mountPath: /etc/alloy/config
      volumes:
      - name: alloy-config
        configMap:
          name: alloy-config
{{- end }}
